import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
 title: "Create Next App",
 description: "Generated by create next app",
};

export default function RootLayout({
 children,
}: Readonly<{
 children: React.ReactNode;
}>) {
 return (
  <html lang="en">
   <body className={` antialiased bg-slate-900`}>
    <header className="p-5 flex items-center justify-center shadow-md shadow-slate-800">
     <Link href={"/"} className="text-3xl font-bold text-center text-white">
      Next Application
     </Link>
    </header>
    {children}
   </body>
  </html>
 );
}
